#sdk: "/Users/lucascampbell-rossen/.rvm/gems/ruby-1.8.7-p357/gems/rhodes-3.3.3"
sdkversion: 3.3.3
name: RemoteTest
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.remotetest
  BundleURLScheme: remotetest
wp:
  productid: '9f782180-e0e3-012f-c168-70cd60f27196'
symbian:
  uid: '0xe0a30c4d'
android:
  version: 2.1

extensions: ["json", "another-extension"]
